# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.
include: "rules/common.smk"
include: "rules/genecovr.smk"
include: "rules/gmap.smk"
include: "rules/btk.smk"
include: "rules/utils.smk"

##############################
## Report
##############################
report: "report/workflow.rst"

# Allow users to fix the underlying OS via singularity.
container: "docker://continuumio/miniconda3"

rule all:
    input: unpack(all)
