repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
  - repo: https://github.com/snakemake/snakefmt
    rev: v0.8.5
    hooks:
      - id: snakefmt
  - repo: local
    hooks:
      - id: lint
        name: Snakemake lint
        entry: snakemake --lint text
        language: system
        files: ''
