assemblies: config/assemblies.tsv
transcripts: config/transcripts.tsv
reads: config/reads.tsv
datasources: config/datasources.tsv


genecovr:
  dataset1:
    csvfile: config/genecovr.csv
  dataset2:
    assemblies: ["foo_v1", "foo_v2"]
    transcripts: ["A", "B"]

busco:
  lineage: viridiplantae_odb10
  ids: ["foo_v1"]

jellyfish:
  kmer: [21]
  ids: ["foo_v1"]

quast:
  ids: ["foo_v2"]

kraken2:
  ids: ["foo_v1"]
  db: resources/kraken2db
  npartitions: 2
