assemblies: config/assemblies.yaml
transcripts: config/transcripts.tsv
reads: config/reads.tsv
datasources: config/datasources.tsv

tools:
  genecovr: true
  busco:
    lineage: viridiplantae_odb10
  kraken2:
    db: resources/kraken2db
    npartitions: 1


analysis/small:
  assembly_ids: ["foo_v1"]
  tools:
    busco:
      lineage: viridiplantae_odb10
    kraken2:
      db: resources/kraken2db
      npartitions: 2
    jellyfish:
      kmer: [21]
      count_pairs: true
      npartitions: 2
    quast: true
    genecovr: true
