$schema: "http://json-schema.org/draft-07/schema#"

description: snakemake configuration file

type: object

properties:

  assemblies:
    type: string
    pattern: .+\.(tsv|yaml)

  transcripts:
    type: [string, 'null']
    pattern: .+\.(tsv|yaml)
    default: null

  reads:
    type: [string, 'null']
    pattern: .+\.(tsv|yaml)
    default: null

  datasources:
    type: [string, 'null']
    pattern: .+\.(tsv|yaml)
    default: null

  fs:
    default: {}
    $ref: "definitions.schema.yaml#/definitions/fs"

  ##############################
  # Resources, rules and tools
  ##############################
  resources.default:
    default: {}
    $ref: "definitions.schema.yaml#/definitions/resources.default"

  rules:
    $ref: "definitions.schema.yaml#/definitions/rules.config"

  tools:
    $ref: "tools.schema.yaml#/definitions/tools.config"

  ##############################
  # Assembly, read and transcript identifiers
  ##############################
  read_ids:
    $ref: "definitions.schema.yaml#/definitions/ids"
    description: read ids
  assembly_ids:
    $ref: "definitions.schema.yaml#/definitions/ids"
    description: assembly ids
  transcript_ids:
    $ref: "definitions.schema.yaml#/definitions/ids"
    description: transcript ids


##############################
# Analysis
##############################
patternProperties:
  '^analysis/[0-9a-zA-Z\-_]+$':
    type: object
    $ref: "definitions.schema.yaml#/definitions/analysis"

additionalProperties: false
required:
  - assemblies
