$schema: "http://json-schema.org/draft-07/schema#"

description: snakemake configuration file

type: object

properties:

  assemblies:
    type: string

  transcripts:
    type: [string, 'null']
    default: null

  reads:
    type: [string, 'null']
    default: null

  datasources:
    type: [string, 'null']
    default: null

  fs:
    $ref: "definitions.schema.yaml#/definitions/fs"
    default: {}

  ##############################
  # Workflow: top-level configurations for each application
  ##############################
  jellyfish:
    $ref: "jellyfish.schema.yaml#/definitions/jellyfish.config"
  busco:
    $ref: "busco.schema.yaml#/definitions/busco.config"
  quast:
    $ref: "quast.schema.yaml#/definitions/quast.config"
  btk:
    $ref: "btk.schema.yaml#/definitions/btk.config"
  genecovr:
    default: {}
    $ref: "genecovr.schema.yaml#/definitions/genecovr.config"

  ##############################
  # Resources and rules
  ##############################
  resources.default:
    $ref: "definitions.schema.yaml#/definitions/resources.default"
    default: {}

  resources:
    $ref: "definitions.schema.yaml#/definitions/resources"
    default: {}


additionalProperties: false
required:
  - assemblies
