$schema: "http://json-schema.org/draft-07/schema#"

description: snakemake configuration file

type: object

properties:
  assemblies:
    type: string
  transcripts:
    type: [string, 'null']
    default: null
  reads:
    type: [string, 'null']
    default: null
  fs:
    $ref: "definitions.schema.yaml#/definitions/fs"
    default: {}
  gmap:
    $ref: "gmap.schema.yaml#/definitions/gmap"
    default: {}
  btk:
    $ref: "btk.schema.yaml#/definitions/btk"
    default: {}
  genecovr:
    $ref: "genecovr.schema.yaml#/definitions/genecovr"
    default: {}

additionalProperties: false
required:
  - assemblies
