$schema: "http://json-schema.org/draft-07/schema#"

description: snakemake configuration file

type: object

properties:

  assemblies:
    type: string

  transcripts:
    type: [string, 'null']
    default: null

  reads:
    type: [string, 'null']
    default: null

  datasources:
    type: [string, 'null']
    default: null

  fs:
    $ref: "definitions.schema.yaml#/definitions/fs"
    default: {}

  ##############################
  # Workflow: top-level configurations for each application
  ##############################
  jellyfish:
    type: object
    $ref: "jellyfish.schema.yaml#/definitions/jellyfish"
  busco:
    type: object
    $ref: "busco.schema.yaml#/definitions/busco"
  quast:
    type: string
  btk:
    type: object
    $ref: "btk.schema.yaml#/definitions/btk"
  genecovr:
    type: object
    default: {}
    $ref: "genecovr.schema.yaml#/definitions/genecovr_workflow"

  # FIXME: tools could also list assemblies by id such that one could
  # exclude assemblies for a tool
  tools:
    type: array
    description: >-
      List of tools that lack configuration options. Listing a tool
      here will run it.
    items:
      type: string
      uniqueItems: true
      enum:
        - quast

  ##############################
  # Resources and rules
  ##############################
  resources.default:
    $ref: "definitions.schema.yaml#/definitions/resources.default"
    default: {}

  resources:
    $ref: "definitions.schema.yaml#/definitions/resources"
    default: {}


additionalProperties: false
required:
  - assemblies
