name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches_ignore: []

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Lint workflow
      uses: snakemake/snakemake-github-action@v1.25.1
      with:
        directory: .
        snakefile: workflow/Snakefile
        args: "--lint"
        stagein: micromamba install -y -c conda-forge -c anaconda rsync conda
  Testing:
    runs-on: ubuntu-latest
    needs: Linting
    timeout-minutes: 30
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
    - name: Test workflow (local test data)
      uses: snakemake/snakemake-github-action@v1.25.1
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--use-conda --show-failed-logs -j 10 --retries 1 --rerun-incomplete --keep-going --conda-cleanup-pkgs cache --wrapper-prefix file:///github/workspace/workflow/wrappers"
        stagein: micromamba install -y -c conda-forge -c anaconda rsync conda
    - name: Test report
      uses: snakemake/snakemake-github-action@v1.25.1
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--report report.zip --wrapper-prefix file:///github/workspace/workflow/wrappers"
        stagein: micromamba install -y -c conda-forge -c anaconda rsync conda
